
const translations={
es:{
  brand:"SUMMA PRODUCTS", tag:"logo aquí", nav_who:"Quiénes somos", nav_brands:"Nuestras marcas", nav_services:"Qué hacemos", nav_channels:"Canales", nav_process:"Cómo trabajamos", nav_faq:"Preguntas", nav_contact:"Contacto",
  cta_header:"Quiero que vendan mi producto", hero_eyebrow:"Para fabricantes y dueños de marca", hero_title:"Tu producto es bueno. Lo que falta es quien lo sepa vender en México.", hero_lead:"Desde 2019 construimos y vendemos marcas en once canales digitales de México, Estados Unidos y Canadá. Compramos, almacenamos, listamos, anunciamos, enviamos y damos servicio al cliente. Tú fabricas: nosotros nos encargamos del canal digital completo.", cta_primary:"Quiero que vendan mi producto", cta_secondary:"Conoce a Summa", hero_channels_label:"Vendemos en:", hero_shopify:"Tiendas propias en Shopify",
  metric_since:"Vendiendo marcas desde", metric_brands:"Marcas propias que operamos", metric_skus:"SKUs activos en catálogo", metric_units:"Unidades vendidas al mes en Amazon", metric_reviews:"Reseñas de clientes en marketplaces", metric_channels:"Canales de venta operados", metric_note:"Las unidades corresponden a temporada normal; en temporada alta el volumen se duplica. Cifras a agosto de 2026.",
  who_eyebrow:"Quiénes somos", who_title:"No somos una agencia. Somos el socio comercial que compra, vende y responde.", who_p1:"Summa Products empezó en 2019 con una sola marca, cuatro productos y una sola tienda: Amazon Estados Unidos. Hoy operamos cuatro marcas, más de 50 SKUs activos y once canales de venta en México, Estados Unidos y Canadá, con más de mil reseñas de clientes acumuladas en los marketplaces.", who_p2:"Ese crecimiento no salió de un presupuesto grande. Salió de aprender a vender producto por producto: qué listado convierte, cuánto aguanta un precio, cuándo reponer inventario antes de quebrar el stock, qué campaña deja margen y cuál solo quema dinero. Lo hicimos con capital propio, así que cada error lo pagamos nosotros.", who_p3:"Por eso no te cobramos una cuota por asesorarte. Compramos tu producto, lo tenemos en nuestra bodega y asumimos el riesgo de venderlo. Trabajamos desde {{CIUDAD}} con bodega propia y un equipo interno que cubre compras, catálogo, publicidad, logística y atención a clientes.",
  growth_then_label:"Cuando arrancamos · 2019", growth_then_1:"1 marca", growth_then_2:"4 productos", growth_then_3:"1 canal (Amazon USA)", growth_then_4:"1 país", growth_now_label:"Hoy", growth_now_1:"4 marcas", growth_now_2:"+50 SKUs activos", growth_now_3:"11 canales", growth_now_4:"3 países", warehouse_note:"Reemplazar con foto real de bodega / empaque",
  pillar_1_title:"Operación propia", pillar_1_text:"Bodega, inventario y empaque manejados por nosotros. No dependemos de terceros para surtir.", pillar_2_title:"Decisiones con datos", pillar_2_text:"Planeamos inventario y precio con análisis semanal de venta real por canal, no con corazonadas.", pillar_3_title:"Un solo interlocutor", pillar_3_text:"Un contacto directo por marca. Sin pasar por cuatro áreas para resolver un pedido.",
  brands_eyebrow:"Nuestras marcas", brands_title:"Antes de vender la tuya, aprendimos vendiendo las nuestras.", brands_lead:"Operamos cuatro marcas propias desde 2019. Cada una la construimos desde cero: catálogo, listados, publicidad, inventario y servicio al cliente. Cuando te decimos qué funciona en un canal, no es teoría de agencia: es lo que aprendimos arriesgando nuestro propio capital.", brand_logo_placeholder:"logo aquí", brand_1_tag:"Calcetería", brand_1_desc:"{{UNA LÍNEA SOBRE LA MARCA}}", brand_2_tag:"Suplementos alimenticios", brand_2_desc:"{{UNA LÍNEA SOBRE LA MARCA}}", brand_3_tag:"{{CATEGORÍA}}", brand_3_desc:"{{UNA LÍNEA SOBRE LA MARCA}}", brand_4_tag:"{{CATEGORÍA}}", brand_4_desc:"{{UNA LÍNEA SOBRE LA MARCA}}",
  services_eyebrow:"Qué hacemos", services_title:"Todo lo que hay entre tu bodega y el cliente final, lo hacemos nosotros.", service_1_title:"Listados que sí venden", service_1_text:"Fotografía, títulos, viñetas, A+ Content y fichas técnicas optimizadas para búsqueda en cada marketplace.", service_2_title:"Publicidad y posicionamiento", service_2_text:"Manejamos campañas de Amazon Ads, Mercado Ads y TikTok con presupuesto propio y seguimiento de rentabilidad por producto.", service_3_title:"Inventario y logística", service_3_text:"Recibimos en bodega, enviamos a Amazon FBA y Mercado Libre Full, y reponemos antes de que se agote.", service_4_title:"Precio y control de canal", service_4_text:"Cuidamos que tu marca no se canibalice entre canales y peleamos el Buy Box sin destruir tu precio de lista.", service_5_title:"Atención al cliente y reseñas", service_5_text:"Contestamos preguntas, resolvemos devoluciones y trabajamos la reputación de tu producto.", service_6_title:"Reportes claros", service_6_text:"Sabes qué se vendió, en qué canal y a qué ritmo. Sin pedirlo tres veces.",
  channels_eyebrow:"Dónde vendemos", channels_title:"Once canales, una sola operación.", channels_lead:"Empezamos en uno y hoy operamos once. Cada canal tiene su propio cliente, su propia logística y sus propias reglas de precio. Los manejamos todos desde una sola bodega y un solo equipo, así tu marca no compite contra sí misma.", ch_1_tag:"Marketplace · Estados Unidos", ch_1_text:"Donde arrancamos en 2019. Puerta de entrada al mercado estadounidense sin que abras operación allá.", ch_2_tag:"Marketplace · México", ch_2_text:"El canal de mayor volumen del país. Inventario en FBA y campañas activas.", ch_3_tag:"Marketplace · Canadá", ch_3_text:"El tercer mercado de Norteamérica, con la misma cuenta y la misma logística que ya operamos.", ch_4_tag:"Marketplace · México", ch_4_text:"Operación con Mercado Envíos Full para entrega en el día.", ch_5_tag:"Retail departamental", ch_5_text:"Marketplace del departamental con el cliente de mayor ticket promedio.", ch_6_tag:"Retail departamental", ch_6_text:"Complementario a Liverpool, con perfil de cliente similar y menos competencia por categoría.", ch_7_tag:"Retail departamental", ch_7_text:"Alcance al cliente de crédito y a plazas donde el marketplace tradicional no llega.", ch_8_tag:"Autoservicio", ch_8_text:"Marketplace de crecimiento acelerado en México, con un cliente distinto al de Amazon.", ch_9_tag:"Social commerce", ch_9_text:"Venta por contenido y video. El canal donde un producto nuevo se descubre, no se busca.", ch_10_tag:"Marketplace", ch_10_text:"{{DESCRIPCIÓN DE CRONIA}}", ch_11_tag:"Canal directo", ch_11_text:"Sin comisión de marketplace. Aquí controlamos promociones, lanzamientos y precio de lista.",
  process_eyebrow:"Cómo trabajamos", process_title:"De la primera llamada al primer pedido, en semanas.", step_1_title:"Contacto", step_1_text:"Nos mandas tu catálogo, precios de mayoreo y volúmenes disponibles.", step_2_title:"Evaluación", step_2_text:"Analizamos demanda, competencia y margen real en cada canal. Te decimos de frente si tu producto tiene lugar o no.", step_3_title:"Pedido piloto", step_3_text:"Arrancamos con una compra inicial acotada para probar rotación sin riesgo grande para nadie.", step_4_title:"Escala", step_4_text:"Si rota, subimos volumen, abrimos más canales y metemos presupuesto de publicidad.",
  fit_eyebrow:"Perfil que buscamos", fit_title:"Somos selectivos, y eso te conviene.", fit_lead:"No metemos todo a nuestro catálogo. Cada producto que subimos compite con nuestra propia atención y nuestro propio capital. Esto es lo que hace que una marca encaje con nosotros:", fit_yes_title:"Encaja bien", fit_yes_1:"Capacidad de surtir con consistencia y tiempos claros de entrega.", fit_yes_2:"Precio de mayoreo que deje margen después de comisiones de marketplace y envío.", fit_yes_3:"Producto con documentación en orden: código de barras, ficha técnica, empaque en condiciones.", fit_yes_4:"Disposición a cuidar el canal digital y no reventar el precio con diez vendedores más.", fit_no_title:"Todavía no", fit_no_1:"Producto sin inventario disponible ni fecha de producción.", fit_no_2:"Márgenes que solo funcionan vendiendo a consignación.", fit_no_3:"Categorías con restricción regulatoria que no podemos cubrir todavía.",
  faq_eyebrow:"Preguntas de proveedores", faq_title:"Lo que casi siempre nos preguntan.", faq_1_q:"¿Compran o trabajan a consignación?", faq_1_a:"Compramos. Emitimos orden de compra y pagamos según las condiciones que acordemos por escrito.", faq_2_q:"¿Necesito tener cuenta de vendedor en Amazon o Mercado Libre?", faq_2_a:"No. Vendemos bajo nuestras cuentas, ya establecidas desde 2019 y con más de mil reseñas de clientes acumuladas. Tú no administras nada de la plataforma.", faq_3_q:"¿Trabajan con marcas que ya se venden en línea?", faq_3_a:"Sí, siempre que haya reglas claras de canal y de precio para que no nos peleemos entre nosotros.", faq_4_q:"¿Aceptan marcas extranjeras sin operación en México?", faq_4_a:"Sí. Es uno de los casos donde más aportamos: entrada al mercado mexicano sin que abras entidad ni bodega aquí.", faq_5_q:"¿Cuánto tarda en estar mi producto publicado?", faq_5_a:"Depende de la categoría y de la documentación, normalmente semanas, no meses, una vez recibido el inventario.", faq_6_q:"¿Entran a todos los canales desde el principio?", faq_6_a:"No. Arrancamos en los canales donde el producto tiene la mejor probabilidad de rotar y abrimos el resto conforme se confirma la demanda.", faq_7_q:"Si ya tienen marcas propias, ¿van a competir con la mía?", faq_7_a:"Nuestras cuatro marcas viven en categorías definidas y no las usamos para copiar producto de proveedores. Si tu producto compite de frente con alguna, te lo decimos en la primera llamada en lugar de que lo descubras seis meses después.", faq_8_q:"¿En qué categorías tienen experiencia?", faq_8_a:"Calcetería, suplementos alimenticios y {{OTRAS CATEGORÍAS}}. Nuestras cuatro marcas propias operan en esas categorías, así que ahí conocemos al cliente, la competencia y el costo real de vender.",
  contact_eyebrow:"Hablemos", contact_title:"¿Quieres que vendamos tu producto? Escríbenos.", contact_lead:"Mándanos tu catálogo y tu lista de precios de mayoreo. Si hay potencial, te contestamos con un análisis del canal, no con un correo automático.", contact_email_label:"Correo — la vía más rápida", contact_email_hint:"Mándanos catálogo y lista de precios de mayoreo.", contact_whatsapp_label:"WhatsApp", contact_whatsapp_hint:"Atención a proveedores", contact_whatsapp_cta:"Escribir por WhatsApp", contact_hours_label:"Horario y ubicación",
  form_name:"Nombre completo", form_company:"Empresa o marca", form_email:"Correo", form_phone:"Teléfono / WhatsApp", form_category:"Categoría de producto", form_category_placeholder:"Consumo", form_cat_hogar:"Hogar", form_cat_belleza:"Belleza y cuidado personal", form_cat_suplementos:"Suplementos alimenticios", form_cat_deportes:"Deportes", form_cat_otro:"Otro", form_volume:"Volumen mensual que puedes surtir", form_volume_placeholder:"Menos de 500 unidades", form_vol_500_2000:"500 – 2,000", form_vol_2000_10000:"2,000 – 10,000", form_vol_10000_plus:"Más de 10,000", form_online:"¿Ya se vende en línea en México?", form_online_placeholder:"Sí", form_online_no:"No", form_message:"Mensaje", form_submit:"Enviar", form_privacy:"Usamos tus datos solo para evaluar la oportunidad comercial. No los compartimos con terceros.",
  footer_desc:"Operamos y vendemos marcas en los principales canales digitales de México, Estados Unidos y Canadá.", footer_nav_title:"Navegación", footer_contact_title:"Contacto", footer_legal:"© 2026 Summa Products. {{RAZÓN SOCIAL}}.", footer_privacy:"Aviso de Privacidad", footer_terms:"Términos"
},
en:{
  brand:"SUMMA PRODUCTS", tag:"logo here", nav_who:"Who we are", nav_brands:"Our brands", nav_services:"What we do", nav_channels:"Channels", nav_process:"How we work", nav_faq:"FAQ", nav_contact:"Contact",
  cta_header:"I want you to sell my product", hero_eyebrow:"For manufacturers and brand owners", hero_title:"Your product is good. What it needs is someone who knows how to sell it in Mexico.", hero_lead:"Since 2019 we have built and sold brands across eleven digital channels in Mexico, the United States and Canada. We buy, store, list, advertise, ship and handle customer service. You manufacture; we handle the entire digital channel.", cta_primary:"I want you to sell my product", cta_secondary:"Meet Summa", hero_channels_label:"We sell on:", hero_shopify:"Owned Shopify stores",
  metric_since:"Selling brands since", metric_brands:"Owned brands we operate", metric_skus:"Active SKUs in catalog", metric_units:"Units sold per month on Amazon", metric_reviews:"Customer reviews on marketplaces", metric_channels:"Sales channels operated", metric_note:"Units reflect normal season; high season doubles the volume. Figures as of August 2026.",
  who_eyebrow:"Who we are", who_title:"We are not an agency. We are the trading partner that buys, sells and answers.", who_p1:"Summa Products started in 2019 with one brand, four products and one store: Amazon United States. Today we operate four brands, more than 50 active SKUs and eleven sales channels in Mexico, the United States and Canada, with more than a thousand customer reviews accumulated on the marketplaces.", who_p2:"That growth did not come from a big budget. It came from learning to sell product by product: which listing converts, how much a price can hold, when to restock inventory before breaking stock, which campaign leaves margin and which one only burns money. We did it with our own capital, so every mistake cost us.", who_p3:"That is why we do not charge you a fee to advise you. We buy your product, keep it in our warehouse and assume the risk of selling it. We work from {{CIUDAD}} with our own warehouse and an internal team covering purchasing, catalog, advertising, logistics and customer service.",
  growth_then_label:"When we started · 2019", growth_then_1:"1 brand", growth_then_2:"4 products", growth_then_3:"1 channel (Amazon USA)", growth_then_4:"1 country", growth_now_label:"Today", growth_now_1:"4 brands", growth_now_2:"+50 active SKUs", growth_now_3:"11 channels", growth_now_4:"3 countries", warehouse_note:"Replace with real warehouse / packaging photo",
  pillar_1_title:"Own operation", pillar_1_text:"Warehouse, inventory and packaging handled by us. We do not depend on third parties to fulfill.", pillar_2_title:"Data-driven decisions", pillar_2_text:"We plan inventory and price with weekly analysis of actual sales per channel, not hunches.", pillar_3_title:"One point of contact", pillar_3_text:"One direct contact per brand. No passing through four departments to solve an order.",
  brands_eyebrow:"Our brands", brands_title:"Before selling yours, we learned by selling our own.", brands_lead:"We have operated four owned brands since 2019. We built each one from scratch: catalog, listings, advertising, inventory and customer service. When we tell you what works on a channel, it is not agency theory: it is what we learned risking our own capital.", brand_logo_placeholder:"logo here", brand_1_tag:"Socks", brand_1_desc:"{{UNA LÍNEA SOBRE LA MARCA}}", brand_2_tag:"Dietary supplements", brand_2_desc:"{{UNA LÍNEA SOBRE LA MARCA}}", brand_3_tag:"{{CATEGORÍA}}", brand_3_desc:"{{UNA LÍNEA SOBRE LA MARCA}}", brand_4_tag:"{{CATEGORÍA}}", brand_4_desc:"{{UNA LÍNEA SOBRE LA MARCA}}",
  services_eyebrow:"What we do", services_title:"Everything between your warehouse and the end customer, we do.", service_1_title:"Listings that actually sell", service_1_text:"Photography, titles, bullets, A+ Content and technical sheets optimized for search on each marketplace.", service_2_title:"Advertising and positioning", service_2_text:"We run Amazon Ads, Mercado Ads and TikTok campaigns with our own budget and profitability tracking per product.", service_3_title:"Inventory and logistics", service_3_text:"We receive at our warehouse, ship to Amazon FBA and Mercado Libre Full, and restock before stock runs out.", service_4_title:"Pricing and channel control", service_4_text:"We protect your brand from channel cannibalization and fight for the Buy Box without destroying your list price.", service_5_title:"Customer service and reviews", service_5_text:"We answer questions, handle returns and work on your product's reputation.", service_6_title:"Clear reporting", service_6_text:"You know what sold, on which channel and at what pace. Without asking three times.",
  channels_eyebrow:"Where we sell", channels_title:"Eleven channels, one operation.", channels_lead:"We started with one and today we operate eleven. Each channel has its own customer, its own logistics and its own pricing rules. We manage them all from a single warehouse and a single team, so your brand does not compete against itself.", ch_1_tag:"Marketplace · United States", ch_1_text:"Where we started in 2019. Gateway to the U.S. market without opening operations there.", ch_2_tag:"Marketplace · Mexico", ch_2_text:"The highest-volume channel in the country. Inventory in FBA and active campaigns.", ch_3_tag:"Marketplace · Canada", ch_3_text:"The third North American market, with the same account and logistics we already operate.", ch_4_tag:"Marketplace · Mexico", ch_4_text:"Operation with Mercado Envíos Full for same-day delivery.", ch_5_tag:"Department store retail", ch_5_text:"Marketplace of the department store with the highest average ticket customer.", ch_6_tag:"Department store retail", ch_6_text:"Complementary to Liverpool, with a similar customer profile and less category competition.", ch_7_tag:"Department store retail", ch_7_text:"Reach the credit customer and plazas where the traditional marketplace does not arrive.", ch_8_tag:"Supermarket", ch_8_text:"Fast-growing marketplace in Mexico, with a customer different from Amazon's.", ch_9_tag:"Social commerce", ch_9_text:"Sales through content and video. The channel where a new product is discovered, not searched for.", ch_10_tag:"Marketplace", ch_10_text:"{{DESCRIPCIÓN DE CRONIA}}", ch_11_tag:"Direct channel", ch_11_text:"No marketplace commission. Here we control promotions, launches and list price.",
  process_eyebrow:"How we work", process_title:"From first call to first order, in weeks.", step_1_title:"Contact", step_1_text:"You send us your catalog, wholesale prices and available volumes.", step_2_title:"Evaluation", step_2_text:"We analyze demand, competition and real margin on each channel. We tell you upfront if your product has a place or not.", step_3_title:"Pilot order", step_3_text:"We start with a limited initial purchase to test turnover without big risk for anyone.", step_4_title:"Scale", step_4_text:"If it turns, we increase volume, open more channels and add advertising budget.",
  fit_eyebrow:"Profile we look for", fit_title:"We are selective, and that is good for you.", fit_lead:"We do not add everything to our catalog. Every product we upload competes for our own attention and our own capital. This is what makes a brand fit with us:", fit_yes_title:"Good fit", fit_yes_1:"Ability to supply consistently with clear delivery times.", fit_yes_2:"Wholesale price that leaves margin after marketplace and shipping fees.", fit_yes_3:"Product with documentation in order: barcode, technical sheet, packaging in good condition.", fit_yes_4:"Willingness to protect the digital channel and not blow up the price with ten other sellers.", fit_no_title:"Not yet", fit_no_1:"Product with no available inventory or production date.", fit_no_2:"Margins that only work on consignment.", fit_no_3:"Categories with regulatory restrictions we cannot cover yet.",
  faq_eyebrow:"Supplier questions", faq_title:"What we are almost always asked.", faq_1_q:"Do you buy or work on consignment?", faq_1_a:"We buy. We issue a purchase order and pay according to the terms we agree in writing.", faq_2_q:"Do I need a seller account on Amazon or Mercado Libre?", faq_2_a:"No. We sell under our accounts, established since 2019 and with more than a thousand accumulated customer reviews. You do not manage any platform.", faq_3_q:"Do you work with brands already sold online?", faq_3_a:"Yes, as long as there are clear channel and pricing rules so we do not fight each other.", faq_4_q:"Do you accept foreign brands with no operation in Mexico?", faq_4_a:"Yes. It is one of the cases where we add the most value: entry into the Mexican market without opening an entity or warehouse here.", faq_5_q:"How long until my product is live?", faq_5_a:"It depends on the category and documentation, usually weeks, not months, once inventory is received.", faq_6_q:"Do you launch on all channels from the start?", faq_6_a:"No. We start on the channels where the product has the best chance of turning and open the rest as demand is confirmed.", faq_7_q:"If you already have own brands, will you compete with mine?", faq_7_a:"Our four brands live in defined categories and we do not use them to copy supplier products. If your product directly competes with one, we tell you on the first call instead of you finding out six months later.", faq_8_q:"What categories do you have experience in?", faq_8_a:"Socks, dietary supplements and {{OTRAS CATEGORÍAS}}. Our four own brands operate in those categories, so there we know the customer, the competition and the real cost of selling.",
  contact_eyebrow:"Let's talk", contact_title:"Want us to sell your product? Write to us.", contact_lead:"Send us your catalog and your wholesale price list. If there is potential, we reply with a channel analysis, not an automated email.", contact_email_label:"Email — the fastest way", contact_email_hint:"Send us your catalog and wholesale price list.", contact_whatsapp_label:"WhatsApp", contact_whatsapp_hint:"Supplier support", contact_whatsapp_cta:"Write on WhatsApp", contact_hours_label:"Hours and location",
  form_name:"Full name", form_company:"Company or brand", form_email:"Email", form_phone:"Phone / WhatsApp", form_category:"Product category", form_category_placeholder:"Consumer", form_cat_hogar:"Home", form_cat_belleza:"Beauty & personal care", form_cat_suplementos:"Dietary supplements", form_cat_deportes:"Sports", form_cat_otro:"Other", form_volume:"Monthly volume you can supply", form_volume_placeholder:"Less than 500 units", form_vol_500_2000:"500 – 2,000", form_vol_2000_10000:"2,000 – 10,000", form_vol_10000_plus:"More than 10,000", form_online:"Already sold online in Mexico?", form_online_placeholder:"Yes", form_online_no:"No", form_message:"Message", form_submit:"Send", form_privacy:"We only use your data to evaluate the commercial opportunity. We do not share it with third parties.",
  footer_desc:"We operate and sell brands on the main digital channels in Mexico, the United States and Canada.", footer_nav_title:"Navigation", footer_contact_title:"Contact", footer_legal:"© 2026 Summa Products. {{RAZÓN SOCIAL}}.", footer_privacy:"Privacy Notice", footer_terms:"Terms"
}
};
function setLang(l){
  document.documentElement.lang=l;
  document.querySelectorAll('.lang button').forEach(b=>{b.classList.toggle('on',b.dataset.lang===l);b.setAttribute('aria-pressed',b.dataset.lang===l);});
  document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[l][k])el.textContent=translations[l][k];});
  localStorage.setItem('summa-lang',l);
}
document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
setLang(localStorage.getItem('summa-lang')||'es');

const subj='Quiero que Summa venda mi producto';
const body='Hola,\n\nMe interesa que Summa Products venda mi producto en sus canales.\n\nMarca / empresa: \nCategoría: \nVolumen mensual que puedo surtir: \n\nAdjunto mi catálogo y lista de precios de mayoreo.\n\nSaludos,';
document.querySelector('.ccard a[href^="mailto"]').href='mailto:admin@summaproducts.com?subject='+encodeURIComponent(subj)+'&body='+encodeURIComponent(body);

const hd=document.getElementById('hd');
addEventListener('scroll',()=>hd.classList.toggle('solid',scrollY>60));

const io=new IntersectionObserver(e=>e.forEach(x=>x.isIntersecting&&x.target.classList.add('in')),{threshold:.12});
document.querySelectorAll('.rev').forEach(el=>io.observe(el));
